name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile report
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: report
          root_file: main.tex

      - name: Compile paper review
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: paper-review
          root_file: main.tex

      - name: Compile presentation
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: presentation
          root_file: Main.tex

      - name: Install Lean
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          echo "${HOME}/.elan/bin" >> $GITHUB_PATH

      - name: Cache scala tools
        uses: coursier/cache-action@v6

      - name: Install scala tools
        uses: coursier/setup-action@v1
        with:
          apps: sbtn scalafmt

      - name: Check project formatting
        working-directory: lang/
        run: scalafmt --test

      - name: Run tests
        working-directory: lang/
        run: sbt test

      # left out, takes an hour to compile mathlib
      # - name: Build Lean project
      #   working-directory: lean/
      #   run: lake build
